spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: "jdbc:mysql://localhost/mmt"
    username: "root"
    password: "show0715!"    # 윈도우
    driver-class-name: com.mysql.cj.jdbc.Driver
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: "jdbc:mysql://localhost/mmt"
    username: "root"
    password: "Show0715!"    # 맥북, 배포 서버
    driver-class-name: com.mysql.cj.jdbc.Driver
---
## h2 사용할 때의 코드 (여기에 jpa까지 추가해야 오류 없이 실행될 거야.)
#  datasource:
#    url: "jdbc:h2:mem:mmt;MODE=MYSQL;NON_KEYWORDS=USER"
#    username: "sa"
#    password: ""
#    driver-class-name: org.h2.Driver
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
