-- DROP 순서 : 확률 -> 답안 -> 학습지_문항 -> 학습지, 문항. 학생 -> 사용자. 지식체계 -> 단위개념
DROP TABLE IF EXISTS PROBABILITYS;
DROP TABLE IF EXISTS ANSWERS;
DROP TABLE IF EXISTS TESTS_ITEMS;

DROP TABLE IF EXISTS ITEMS;
DROP TABLE IF EXISTS TESTS;
DROP TABLE IF EXISTS STUDENTS;
DROP TABLE IF EXISTS USERS;

DROP TABLE IF EXISTS KNOWLEDGE_TAGS;
DROP TABLE IF EXISTS CONCEPTS;

-- 단위개념 지울 때
DROP TABLE IF EXISTS ANSWERS;
DROP TABLE IF EXISTS TESTS_ITEMS;
DROP TABLE IF EXISTS ITEMS;
DROP TABLE IF EXISTS KNOWLEDGE_TAGS;
DROP TABLE IF EXISTS CONCEPTS;

-- insert 순서
-- insert_diag_test -> insert_items_missing -> insert_diag_items -> insert_diag_testsitems