INSERT INTO tests (test_name, test_comments) VALUES ('진단평가1', '초등학교 전과정');
INSERT INTO tests (test_name, test_comments) VALUES ('진단평가2', '중학교 1학년');
INSERT INTO tests (test_name, test_comments) VALUES ('진단평가3', '중학교 2학년');
INSERT INTO tests (test_name, test_comments) VALUES ('진단평가4', '중학교 3학년');
INSERT INTO tests (test_name, test_comments) VALUES ('진단평가5', '중학교 전과정');
INSERT INTO tests (test_name, test_comments) VALUES ('진단평가6', '고등학교 수학 상하');
INSERT INTO tests (test_name, test_comments) VALUES ('진단평가7', '고등학교 수1');
INSERT INTO tests (test_name, test_comments) VALUES ('진단평가8', '고등학교 수2');
INSERT INTO tests (test_name, test_comments) VALUES ('진단평가9', '수능공통');
INSERT INTO tests (test_name, test_comments) VALUES ('진단평가10', '수능선택_미적');
INSERT INTO tests (test_name, test_comments) VALUES ('진단평가11', '수능선택_기하');
INSERT INTO tests (test_name, test_comments) VALUES ('진단평가12', '수능선택_확통');
