INSERT INTO tests_items(test_id, item_id, test_item_number) VALUES (13, 5134, 1);
INSERT INTO tests_items(test_id, item_id, test_item_number) VALUES (13, 5135, 2);
INSERT INTO tests_items(test_id, item_id, test_item_number) VALUES (13, 5136, 3);
INSERT INTO tests_items(test_id, item_id, test_item_number) VALUES (13, 5137, 4);
INSERT INTO tests_items(test_id, item_id, test_item_number) VALUES (13, 5138, 5);
INSERT INTO tests_items(test_id, item_id, test_item_number) VALUES (13, 5139, 6);
INSERT INTO tests_items(test_id, item_id, test_item_number) VALUES (13, 5140, 7);
INSERT INTO tests_items(test_id, item_id, test_item_number) VALUES (13, 5141, 8);
INSERT INTO tests_items(test_id, item_id, test_item_number) VALUES (13, 5142, 9);
INSERT INTO tests_items(test_id, item_id, test_item_number) VALUES (13, 5143, 10);
INSERT INTO tests_items(test_id, item_id, test_item_number) VALUES (13, 5144, 10);
INSERT INTO tests_items(test_id, item_id, test_item_number) VALUES (13, 5145, 11);
INSERT INTO tests_items(test_id, item_id, test_item_number) VALUES (13, 5146, 12);
INSERT INTO tests_items(test_id, item_id, test_item_number) VALUES (13, 5147, 12);
INSERT INTO tests_items(test_id, item_id, test_item_number) VALUES (13, 5148, 13);
INSERT INTO tests_items(test_id, item_id, test_item_number) VALUES (13, 5149, 14);
INSERT INTO tests_items(test_id, item_id, test_item_number) VALUES (13, 5150, 14);
INSERT INTO tests_items(test_id, item_id, test_item_number) VALUES (13, 5151, 15);
INSERT INTO tests_items(test_id, item_id, test_item_number) VALUES (13, 5152, 15);
INSERT INTO tests_items(test_id, item_id, test_item_number) VALUES (13, 5153, 16);

INSERT INTO tests_items(test_id, item_id, test_item_number) VALUES (14, 5154, 1);
INSERT INTO tests_items(test_id, item_id, test_item_number) VALUES (14, 5155, 2);
INSERT INTO tests_items(test_id, item_id, test_item_number) VALUES (14, 5156, 3);
INSERT INTO tests_items(test_id, item_id, test_item_number) VALUES (14, 5157, 4);
INSERT INTO tests_items(test_id, item_id, test_item_number) VALUES (14, 5158, 5);
INSERT INTO tests_items(test_id, item_id, test_item_number) VALUES (14, 5159, 6);
INSERT INTO tests_items(test_id, item_id, test_item_number) VALUES (14, 5160, 7);
INSERT INTO tests_items(test_id, item_id, test_item_number) VALUES (14, 5161, 8);
INSERT INTO tests_items(test_id, item_id, test_item_number) VALUES (14, 5162, 9);
INSERT INTO tests_items(test_id, item_id, test_item_number) VALUES (14, 5163, 9);
INSERT INTO tests_items(test_id, item_id, test_item_number) VALUES (14, 5164, 10);
INSERT INTO tests_items(test_id, item_id, test_item_number) VALUES (14, 5165, 11);
INSERT INTO tests_items(test_id, item_id, test_item_number) VALUES (14, 5166, 12);
INSERT INTO tests_items(test_id, item_id, test_item_number) VALUES (14, 5167, 13);
INSERT INTO tests_items(test_id, item_id, test_item_number) VALUES (14, 5168, 14);

select * from tests_items;
